# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

require 'vagrant-aws'

Vagrant.configure(2) do |config|
    #    config.vm.box = "aws-dummy"
    config.vm.provider 'virtualbox' do |virtualbox, override|
        config.vm.box = "gbarbieru/xenial"
        config.vm.network "forwarded_port", guest: 80, host: 8082
    end
    config.vm.provision :shell, path: "bootstrap.sh"
end
